### ISSUE TITLE
Feature Request(?): Support locking for deployment to multiple servers

### ISSUE THREAD

**Issue by joelmellon** [TimoKoerber/laravel-one-time-operations#3]
Congrats on being featured in [Laravel News](https://laravel-news.com/run-one-time-operations-after-deployment-with-laravel)! I've been trying to solve this problem for a while now, so my interested in this package was instantly piqued.

I've perused the source and don't see any sign of locking so that on deployment to multiple servers, the one-time process commands don't step on each other.

My current set up is a Kubernetes deployment with a few web server containers, and a few dedicated task worker containers. Since they're scalable (replicable) I can't configure individual instances to run different commands, so they've all got to do the same exact thing on deployment. (There are other "one-time" possibilities with Kubernetes, but I won't go into detail about my tribulations there. It's been frustrating to say the least.)

Laravel doesn't have any way (that I'm aware of) to run prevent running multiple instances of `artisan migrate` from stepping on each other either, so it's been a problem I'm trying to solve there as well. This package could be leveraged to run migrations, as strange as that sounds, so a feature enhancement here could solve that problem too.

Is there functionality like this that I'm missing, or any plans for something like this in the future?

**Comment by TimoKoerber** [comment]
This is a very specific request with very specific circumstances. When I created the package I wanted to recreate the simplicity of migrations, no more, no less. Adding a lot more features to fit these rare edge-cases would blow up the package unnecessarily and this is not my goal. Sorry.

I also don't really see the necessity for a "locking mechanism". Even if you have multiple servers that run "operations:process", it's "first come first serve". The first execution sets the operations as "processed" so the other ones will ignore it. And since the operations are being executed asynchronously by default there shouldn't be any issues with locking or race conditions.

**Comment by TimoKoerber** [comment]
Of course there are thousand of companies that use multiple servers. But it seems they do not have your specific problem or otherwise Laravel would have found a solution for it, don't you think?

If you run long operations _synchronously_, of course there could be issues with multiples servers. This is why I don't recommend it in the manual and why the default is running them **asynchronously** - this way they are marked as "processed" _instantly_.

**Comment by joelmellon** [comment]
> But it seems they do not have your specific problem or otherwise Laravel would have found a solution for it, don't you think?

There are problems without solutions everywhere. It’s the backbone of capitalism.

You’ve got a strange attitude.

> When I created the package I wanted to recreate the simplicity of migrations, no more, no less.

I recommended adding this note to your readme. I think it will save people a lot of time avoid conversations with you.
