### ISSUE TITLE
Feature request: operation logs

### ISSUE THREAD

**Issue by skovachev** [TimoKoerber/laravel-one-time-operations#4]
Great job on this package! I have a suggestion for a feature for you to consider.
Operations seem to fit the scenario of data migrations. In most cases where I've handled tasks like that, I always try to add some sort of logging capability that shows progress and results. For example, if we're processing a large list of items filtered by some rule I like to output the result for each item processed.
Perhaps we could add a way to do that i.e. have some logging facility available inside an operation that then writes results in the DB table.

**Comment by TimoKoerber** [comment]
Thank you!
I see what you mean. I also thought about some way of logging the result or progress of an operation. The thing is, that the focus of this package is more **launching an operation automatically** (and asynchronously!) rather than "observing" its progress. Once the Operation-Job is dispatched, it should be its "job" (lol) to observe the process. It's kinda like a rocket launching a space shuttle, that has to fly alone at a certain point  🚀 😅 This is also important because a long-running data-migration should not delay (or fail) a deployment. 

So I think you should implement a custom way of logging the process. Since you might sometimes also need this logging-mechanism for data-migrations, that do **not** need to be started automatically, a logging-mechanism should not be coupled to the one-time-operations. #separationsofconcerns
